In [29]:
import pandas as pd
fish = pd.read_csv('https://bit.ly/fish_csv_data')

fish.head()

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [30]:
print(pd.unique(fish['Species']))

['Bream' 'Roach' 'Whitefish' 'Parkki' 'Perch' 'Pike' 'Smelt']


In [31]:
fish_input = fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()

In [32]:
print(fish_input[:5])

[[242.      25.4     30.      11.52     4.02  ]
 [290.      26.3     31.2     12.48     4.3056]
 [340.      26.5     31.1     12.3778   4.6961]
 [363.      29.      33.5     12.73     4.4555]
 [430.      29.      34.      12.444    5.134 ]]


In [33]:
fish_target = fish['Species'].to_numpy()

In [34]:

from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(fish_input, fish_target,random_state=42)

In [35]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn

In [36]:
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(train_input, train_target)

pred_svm = clf_svm.predict(test_input)

print("\n--- SVM Classifier ---")
print(accuracy_score(test_target, pred_svm))
print(confusion_matrix(test_target, pred_svm))


--- SVM Classifier ---
0.475
[[ 8  0  3  0  0  0  0]
 [ 0  0  2  0  0  0  0]
 [ 1  0 11  0  0  0  0]
 [ 2  0  2  0  0  0  0]
 [ 0  0  3  0  0  0  0]
 [ 0  0  5  0  0  0  0]
 [ 0  0  3  0  0  0  0]]


In [37]:
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(train_input, train_target)

pred_lr = clf_lr.predict(test_input)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(test_target, pred_lr))
print (confusion_matrix(test_target, pred_lr))


--- Logistic Regression Classifier ---
0.75
[[11  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0]
 [ 0  0  8  0  4  0  0]
 [ 0  0  0  4  0  0  0]
 [ 0  0  1  0  2  0  0]
 [ 0  0  0  0  0  5  0]
 [ 0  0  3  0  0  0  0]]


In [38]:
clf_nn = MLPClassifier(random_state=0)
clf_nn.fit(train_input, train_target)

pred_nn = clf_nn.predict(test_input)

print ("\n--- Neural Network Classifier ---")
print (accuracy_score(test_target, pred_nn))
print (confusion_matrix(test_target, pred_nn))


--- Neural Network Classifier ---
0.75
[[11  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0]
 [ 0  0 12  0  0  0  0]
 [ 0  0  2  2  0  0  0]
 [ 0  0  3  0  0  0  0]
 [ 0  0  0  0  0  5  0]
 [ 0  0  3  0  0  0  0]]


In [39]:
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(train_input, train_target)

pred_dt = clf_dt.predict(test_input)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(test_target, pred_dt))
print (confusion_matrix(test_target, pred_dt))


--- Decision Tree Classifier ---
0.75
[[11  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0]
 [ 0  0  5  0  7  0  0]
 [ 0  0  0  4  0  0  0]
 [ 0  0  1  0  2  0  0]
 [ 0  0  0  0  0  5  0]
 [ 0  0  0  0  2  0  1]]


In [40]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(train_input, train_target)
pred = rf_clf.predict(test_input)
print(accuracy_score(test_target,pred))
print (confusion_matrix(test_target, pred))


--- Radom Forest ---
0.75
[[11  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0]
 [ 0  0  7  0  5  0  0]
 [ 0  0  0  4  0  0  0]
 [ 0  0  2  0  1  0  0]
 [ 0  0  0  0  0  5  0]
 [ 0  0  2  0  1  0  0]]


In [41]:
import matplotlib.pyplot as plt

k_range = range(1, 201)
find_accuracy = []

for k in k_range:
  find_model = KNeighborsClassifier(n_neighbors = k)
  find_model.fit(train_input, train_target.values.ravel())

  find_accuracy.append(find_model.score(test_input, test_target))
  
plt.plot(k_range, find_accuracy, label="training accuracy")
plt.xlabel("k value")
plt.ylabel("Accuracy")
plt.title("Find Breast Cancer Classifier Accuracy")
plt.show()

NameError: name 'KNeighborsClassifier' is not defined